export type QuizCategory = "오행" | "궁합" | "사주 상식";

export type QuizQuestion = {
  id: number;
  category: QuizCategory;
  question: string;
  optionA: string;
  optionB: string;
  answer: "A" | "B";
  explanation: string;
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  // ─── 오행 (16개) ───────────────────────────────────────────────
  {
    id: 1,
    category: "오행",
    question: "수(水)기운인 사람, 창의력이 막혔을 때는?",
    optionA: "목욕·샤워로 리셋 🚿",
    optionB: "땀 흘리는 운동 🏃",
    answer: "A",
    explanation: "수기운은 물과 연결될 때 아이디어가 자연스럽게 흘러요.",
  },
  {
    id: 2,
    category: "오행",
    question: "화(火)기운이 강한 날, 점심 메뉴 추천은?",
    optionA: "뜨끈한 국물 요리 🍲",
    optionB: "시원한 냉면 🍜",
    answer: "B",
    explanation: "이미 뜨거운 기운이 강한데 열 음식은 과부하를 줄 수 있어요.",
  },
  {
    id: 3,
    category: "오행",
    question: "목(木)기운인 사람, 스트레스 해소 방법은?",
    optionA: "쇼핑 🛍️",
    optionB: "숲 산책 🌲",
    answer: "B",
    explanation: "목기운은 자연, 특히 나무와 연결될 때 에너지가 회복돼요.",
  },
  {
    id: 4,
    category: "오행",
    question: "금(金)기운인 사람, 카페 자리 선택은?",
    optionA: "조용한 창가 자리 🪟",
    optionB: "사람 많은 중앙 자리 👥",
    answer: "A",
    explanation: "금기운은 정밀함과 집중력이 필요해 조용한 환경에서 빛나요.",
  },
  {
    id: 5,
    category: "오행",
    question: "토(土)기운인 사람에게 맞는 여행 스타일은?",
    optionA: "즉흥 배낭여행 🎒",
    optionB: "꼼꼼히 계획한 여행 🗺️",
    answer: "B",
    explanation: "토기운은 안정과 신뢰를 중시해서 계획된 여행을 더 즐겨요.",
  },
  {
    id: 6,
    category: "오행",
    question: "화(火)기운인 사람, 번아웃 왔을 때 회복법은?",
    optionA: "바다 여행 🌊",
    optionB: "사우나로 땀 빼기 💦",
    answer: "A",
    explanation:
      "물기운(수)이 화기운의 열을 식혀줘서 바다가 최고의 처방이에요.",
  },
  {
    id: 7,
    category: "오행",
    question: "수(水)기운인 사람에게 추천하는 운동은?",
    optionA: "복싱 🥊",
    optionB: "수영 🏊",
    answer: "B",
    explanation: "수기운은 물과 흐름을 상징해 수영이 기운을 가장 잘 살려줘요.",
  },
  {
    id: 8,
    category: "오행",
    question: "목(木)기운이 강한 날, 집중 잘 되는 카페 자리는?",
    optionA: "창가 햇빛 자리 🌿",
    optionB: "지하 조용한 자리 🕯️",
    answer: "A",
    explanation: "목기운은 성장하는 나무처럼 빛과 탁 트인 공간이 필요해요.",
  },
  {
    id: 9,
    category: "오행",
    question: "금(金)기운인 사람, 친구와 다퉜을 때 화해 방식은?",
    optionA: "바로 만나서 이야기 🤝",
    optionB: "메시지로 정리해서 전달 📝",
    answer: "B",
    explanation:
      "금기운은 논리적이고 정확해서 말보다 글로 정리할 때 오해가 줄어요.",
  },
  {
    id: 10,
    category: "오행",
    question: "토(土)기운이 강한 날, 에너지 충전 방법은?",
    optionA: "친한 사람들과 집밥 🍚",
    optionB: "혼자 영화 보기 🎬",
    answer: "A",
    explanation: "토기운은 따뜻한 관계와 연결에서 에너지를 얻어요.",
  },
  {
    id: 11,
    category: "오행",
    question: "수(水)기운이 강한 날, 야식 먹어도 될까?",
    optionA: "자제하는 게 낫다 🙅",
    optionB: "야식이 오히려 기운을 살린다 🍗",
    answer: "A",
    explanation: "수기운은 저장의 기운이라 밤에 과식하면 소화에 부담이 돼요.",
  },
  {
    id: 12,
    category: "오행",
    question: "화(火)기운인 사람, 잠들기 어려울 때는?",
    optionA: "따뜻한 허브티 ☕",
    optionB: "시원한 물 한 잔 💧",
    answer: "B",
    explanation: "수기운(물)이 화기운의 열을 식혀주어 숙면을 도와줘요.",
  },
  {
    id: 13,
    category: "오행",
    question: "목(木)기운인 사람의 이상적인 아침 루틴은?",
    optionA: "가벼운 스트레칭 🧘",
    optionB: "바로 커피 한 잔 ☕",
    answer: "A",
    explanation:
      "목기운은 유연하게 뻗어나가는 성질이라 스트레칭으로 기운을 깨워요.",
  },
  {
    id: 14,
    category: "오행",
    question: "금(金)기운이 강한 날, 중요한 결정하기 좋은 환경은?",
    optionA: "조용한 혼자만의 공간 🤍",
    optionB: "친구들과 떠들며 의논 👥",
    answer: "A",
    explanation:
      "금기운은 판단력과 결단력의 기운이라 혼자 차분히 생각할 때 빛나요.",
  },
  {
    id: 15,
    category: "오행",
    question: "토(土)기운인 사람, 주말 에너지 충전 장소는?",
    optionA: "활기찬 시장 구경 🏪",
    optionB: "동네 공원 산책 🌳",
    answer: "B",
    explanation: "토기운은 대지와 안정감이 있는 자연 공간에서 에너지가 차요.",
  },
  {
    id: 16,
    category: "오행",
    question: "수(水)기운인 사람, 이상적인 작업 환경은?",
    optionA: "활기찬 오픈 오피스 🏢",
    optionB: "잔잔한 음악의 조용한 공간 🎶",
    answer: "B",
    explanation: "수기운은 깊이와 고요함에서 창의력과 집중력이 발휘돼요.",
  },

  // ─── 궁합 (18개) ───────────────────────────────────────────────
  {
    id: 17,
    category: "궁합",
    question: "수기운 여자 + 화기운 남자, 첫 데이트 장소는?",
    optionA: "한강 피크닉 🌊",
    optionB: "루프탑 바 🌆",
    answer: "A",
    explanation: "물기운이 두 사람의 기운 차이를 자연스럽게 연결해줘요.",
  },
  {
    id: 18,
    category: "궁합",
    question: "화기운 커플끼리 만났을 때 피해야 할 상황은?",
    optionA: "더운 날 붐비는 페스티벌 🎪",
    optionB: "조용한 전시회 관람 🎨",
    answer: "A",
    explanation:
      "같은 기운이 겹치면 열기가 과해져 작은 일에도 갈등이 생기기 쉬워요.",
  },
  {
    id: 19,
    category: "궁합",
    question: "목기운 + 금기운 커플, 여행 계획은 누가 짜는 게 맞을까?",
    optionA: "목기운 파트너 🌿",
    optionB: "금기운 파트너 ✨",
    answer: "B",
    explanation: "금기운은 꼼꼼함과 계획력이 강해서 여행 계획에 딱 맞아요.",
  },
  {
    id: 20,
    category: "궁합",
    question: "토기운 + 수기운 커플, 집에서 고를 영화 장르는?",
    optionA: "잔잔한 감성 로맨스 🎬",
    optionB: "화려한 액션 블록버스터 💥",
    answer: "A",
    explanation:
      "두 기운 모두 안정감을 선호해 잔잔한 콘텐츠에서 편안함을 느껴요.",
  },
  {
    id: 21,
    category: "궁합",
    question: "금기운 + 수기운 커플, 카페 선택은?",
    optionA: "조용하고 아늑한 카페 ☕",
    optionB: "트렌디하고 사람 많은 카페 🏙️",
    answer: "A",
    explanation:
      "두 기운 모두 집중력과 사색을 즐겨 조용한 공간에서 더 편안해해요.",
  },
  {
    id: 22,
    category: "궁합",
    question: "목기운 + 화기운 커플, 데이트 계획 스타일은?",
    optionA: "큰 틀만 정하고 즉흥적으로 🌟",
    optionB: "시간대별로 빈틈없이 계획 📋",
    answer: "A",
    explanation:
      "목기운의 유연성과 화기운의 즉흥성이 만나면 자유로운 플랜이 잘 맞아요.",
  },
  {
    id: 23,
    category: "궁합",
    question: "화기운 + 금기운 커플, 중요한 결정은 누가?",
    optionA: "화기운 파트너 🔥",
    optionB: "금기운 파트너 ✨",
    answer: "B",
    explanation:
      "화기운은 추진력, 금기운은 판단력이라 중요한 결정은 금기운이 맡는 게 좋아요.",
  },
  {
    id: 24,
    category: "궁합",
    question: "수기운 + 목기운 커플, 첫 여행지는?",
    optionA: "제주도 🌊",
    optionB: "도심 호텔 스테이 🏨",
    answer: "A",
    explanation:
      "수기운의 바다와 목기운의 자연이 만나는 제주가 최고의 궁합이에요.",
  },
  {
    id: 25,
    category: "궁합",
    question: "화기운 + 수기운 커플, 싸운 후 화해 방법은?",
    optionA: "카페에서 차분히 대화 ☕",
    optionB: "운동으로 에너지 발산 후 대화 🏃",
    answer: "A",
    explanation:
      "수기운이 화기운의 열기를 가라앉혀 줘 조용한 공간에서 더 잘 풀려요.",
  },
  {
    id: 26,
    category: "궁합",
    question: "목기운 + 토기운 커플, 주말 나들이 장소는?",
    optionA: "근교 자연 나들이 🚗",
    optionB: "쇼핑몰 데이트 🛍️",
    answer: "A",
    explanation:
      "목기운의 자연 에너지와 토기운의 안정감이 야외 활동에서 조화를 이뤄요.",
  },
  {
    id: 27,
    category: "궁합",
    question: "금기운 + 토기운 커플, 저축 스타일은?",
    optionA: "남는 돈 그때그때 모으기 💰",
    optionB: "구체적 금액·기간 정해서 계획적으로 📊",
    answer: "B",
    explanation:
      "금기운의 정밀함과 토기운의 성실함이 만나면 계획 저축이 가장 잘 맞아요.",
  },
  {
    id: 28,
    category: "궁합",
    question: "수기운 + 토기운 커플, 집 인테리어 콘셉트는?",
    optionA: "모던 블랙&화이트 🖤",
    optionB: "내추럴 우드톤 🪵",
    answer: "B",
    explanation: "수기운의 흐름과 토기운의 안정이 자연 소재에서 잘 어우러져요.",
  },
  {
    id: 29,
    category: "궁합",
    question: "화기운 + 토기운 커플, 서로 응원하는 방식은?",
    optionA: "옆에서 묵묵히 함께 있어주기 🤍",
    optionB: "열정적으로 파이팅 외쳐주기 📣",
    answer: "A",
    explanation:
      "토기운은 안정과 지속성을 중시하고, 화기운도 든든한 지지대를 좋아해요.",
  },
  {
    id: 30,
    category: "궁합",
    question: "목기운 + 수기운 커플, 함께 작업할 공간은?",
    optionA: "활기찬 코워킹 스페이스 💻",
    optionB: "조용한 도서관·스터디카페 📚",
    answer: "B",
    explanation: "두 기운 모두 집중력과 창의력이 고요한 환경에서 발휘돼요.",
  },
  {
    id: 31,
    category: "궁합",
    question: "금기운 + 목기운 커플, 기념일 선물은?",
    optionA: "핸드메이드 감성 선물 🌷",
    optionB: "실용적인 고급 아이템 🎁",
    answer: "B",
    explanation: "금기운이 있는 사람은 품질과 실용성을 중시해요.",
  },
  {
    id: 32,
    category: "궁합",
    question: "토기운 + 금기운 커플, 요리 역할 분담은?",
    optionA: "토기운 재료 준비, 금기운 조리 👨‍🍳",
    optionB: "금기운 재료 준비, 토기운 조리 🍳",
    answer: "A",
    explanation:
      "토기운의 든든함이 재료 준비에, 금기운의 정확함이 조리에 잘 맞아요.",
  },
  {
    id: 33,
    category: "궁합",
    question: "수기운 + 금기운 커플, 기념일 스타일은?",
    optionA: "조용하고 의미 있는 둘만의 저녁 🕯️",
    optionB: "친구들 불러서 파티처럼 성대하게 🎉",
    answer: "A",
    explanation:
      "두 기운 모두 깊이 있고 섬세한 것을 좋아해 조용한 기념일이 더 잘 맞아요.",
  },
  {
    id: 34,
    category: "궁합",
    question: "화기운 + 목기운 커플, 함께 취미 시작한다면?",
    optionA: "캠핑 ⛺",
    optionB: "실내 클라이밍 🧗",
    answer: "A",
    explanation:
      "목기운의 자연 친화성과 화기운의 활동성이 캠핑에서 가장 잘 맞아요.",
  },

  // ─── 사주 상식 (16개) ──────────────────────────────────────────
  {
    id: 35,
    category: "사주 상식",
    question: "사주 '일주(日柱)'는 무엇으로 결정될까?",
    optionA: "태어난 날 📆",
    optionB: "태어난 해 🗓️",
    answer: "A",
    explanation:
      "일주는 태어난 날로 결정되며, 나의 본질적인 성격과 가장 밀접해요.",
  },
  {
    id: 36,
    category: "사주 상식",
    question: "오행 중 봄 기운을 상징하는 것은?",
    optionA: "화(火) 🔥",
    optionB: "목(木) 🌱",
    answer: "B",
    explanation: "목기운은 봄처럼 새로운 시작과 성장을 상징해요.",
  },
  {
    id: 37,
    category: "사주 상식",
    question: "사주 '용신'이란 무엇일까?",
    optionA: "나에게 부족한 기운을 채워주는 요소 ⚖️",
    optionB: "내가 가장 강하게 타고난 기운 💪",
    answer: "A",
    explanation: "용신은 사주의 균형을 맞춰주는 핵심 기운이에요.",
  },
  {
    id: 38,
    category: "사주 상식",
    question: "오행 상생에서 수(水)가 키우는 것은?",
    optionA: "화(火) 🔥",
    optionB: "목(木) 🌳",
    answer: "B",
    explanation: "물이 나무를 키우듯 수생목(水生木)이 상생 관계예요.",
  },
  {
    id: 39,
    category: "사주 상식",
    question: "화기운이 강한 사람이 여름에 더 지치는 이유는?",
    optionA: "같은 기운이 겹쳐 과부하가 생겨서 🌡️",
    optionB: "더위를 유독 많이 타는 체질이어서 ☀️",
    answer: "A",
    explanation: "같은 기운이 두 배로 겹치면 오히려 균형이 무너져 피로해져요.",
  },
  {
    id: 40,
    category: "사주 상식",
    question: "사주 '비겁'이 강한 사람의 특징은?",
    optionA: "배려심이 깊고 희생적이다 🤍",
    optionB: "자존심이 강하고 독립적이다 💪",
    answer: "B",
    explanation: "비겁은 자아, 독립심, 경쟁심과 관련된 기운이에요.",
  },
  {
    id: 41,
    category: "사주 상식",
    question: "오행 중 가을을 상징하는 기운은?",
    optionA: "금(金) ✨",
    optionB: "토(土) 🪨",
    answer: "A",
    explanation: "금기운은 가을처럼 결실과 수확, 정리를 상징해요.",
  },
  {
    id: 42,
    category: "사주 상식",
    question: "사주 '식상'이 강한 사람의 특징은?",
    optionA: "표현력이 풍부하고 창의적이다 🎨",
    optionB: "추진력이 강하고 리더십이 있다 🚀",
    answer: "A",
    explanation: "식상은 자신을 표현하고 창작하는 에너지예요.",
  },
  {
    id: 43,
    category: "사주 상식",
    question: "수기운 강한 사람이 겨울에 특히 조심해야 할 것은?",
    optionA: "번아웃과 과로 ⚡",
    optionB: "지나친 에너지 소비 🏃",
    answer: "A",
    explanation:
      "수기운+겨울 기운이 겹치면 내면으로 파고들어 번아웃이 오기 쉬워요.",
  },
  {
    id: 44,
    category: "사주 상식",
    question: "사주 '관성'이 의미하는 것은?",
    optionA: "창의력과 자유로운 표현 🎨",
    optionB: "책임감과 사회적 역할 📋",
    answer: "B",
    explanation: "관성은 직장, 명예, 사회적 책임과 연결된 기운이에요.",
  },
  {
    id: 45,
    category: "사주 상식",
    question: "오행 상생에서 금(金)이 만드는 것은?",
    optionA: "수(水) 💧",
    optionB: "화(Fire) 🔥",
    answer: "A",
    explanation: "금생수(金生水), 금속에서 물이 나오듯 금이 수를 생해요.",
  },
  {
    id: 46,
    category: "사주 상식",
    question: "사주 '인성'이 강한 사람에게 잘 맞는 활동은?",
    optionA: "영업·네트워킹 📣",
    optionB: "독서·공부·연구 📚",
    answer: "B",
    explanation: "인성은 지식, 학문, 배움의 기운과 연결돼요.",
  },
  {
    id: 47,
    category: "사주 상식",
    question: "화기운이 강한 날 중요한 발표가 있다면?",
    optionA: "에너지가 넘쳐 잘 된다 ⚡",
    optionB: "과열되어 실수하기 쉽다 🌡️",
    answer: "A",
    explanation: "화기운의 카리스마와 추진력이 발표 상황에서 빛을 발해요.",
  },
  {
    id: 48,
    category: "사주 상식",
    question: "오행 상극에서 금(金)을 이기는 것은?",
    optionA: "화(火) 🔥",
    optionB: "수(水) 💧",
    answer: "A",
    explanation: "불이 금속을 녹이듯 화극금(火剋金) 관계예요.",
  },
  {
    id: 49,
    category: "사주 상식",
    question: "사주 '재성'이 강한 사람의 특징은?",
    optionA: "현실적이고 실용적 판단을 잘 한다 💰",
    optionB: "이상적이고 감성적인 편이다 🌙",
    answer: "A",
    explanation: "재성은 재물운과 현실적 처세술에 뛰어난 기운이에요.",
  },
  {
    id: 50,
    category: "사주 상식",
    question: "오행 중 여름을 상징하는 기운은?",
    optionA: "토(土) 🪨",
    optionB: "화(火) 🔥",
    answer: "B",
    explanation: "화기운은 여름처럼 열정과 활발함, 성장을 상징해요.",
  },
];
